package com.appforschool.utils

/**
 * Class Contains All the Constant Values which will be used through out App
 */
class Constant {

    companion object {
        const val DATE_FORMAT = "dd/MM/yy h:mm"
        const val DATE_FORMAT_ONE = "yyyy-MM-dd'T'HH:mm:ss"
        const val DATE_FORMAT_YY_MM_DD = "yyyy-MM-dd"
        const val CHECK_INTERNET = "Please check your internet connection"
        const val DEFAULT_SERVER_ERROR = "Something went wrong on server side. Please try again."
        const val APP_PREFERENCES = "app_preferences"
        const val SOCKET_TIMEOUT_EXCEPTIONS = "Poor connectivity. Please try again later."
        const val CONNECTION_TIMEOUT_EXCEPTIONS = "Connection Timeout Exception"
        const val SUCCESS_CODE = 200
        const val UNAUTHORIZED_CODE = 401
        const val INTERNAL_SERVER_ERROR_CODE = 500
        const val NO_DATA_FOUND_CODE = 404
        const val METHOD_NOT_ALLOW = 405
        const val RESPONSE_MESSAGE = "message"
        const val TWITTER_NAME = "pented_learning"
        const val KEY_ROOM_URL = ""
        const val JITSI_MEET_URL = "https://meet.fahm-technologies.com"
        const val REQUEST_USERNAME = "username"
        const val REQUEST_PASSWORD = "password"
        const val REQUEST_STUDENTID = "studentid"
        const val WEBVIEW_URL = "webview_url"
        const val IS_HOST = "is_host"
        const val REQUEST_USER_TYPE = "usertype"
        const val REQUEST_MODE = "Mode"
        const val REUQEST_MODE_GET_SUBJECT_FILES = "getsubjectfiles"
        const val REUQEST_MODE_GET_ASSIGNMENT = "getassignments"
        const val REUQEST_SUBJECT_ID = "subjectid"
        const val REUQEST_USER_ID = "userid"
        const val REQUEST_GET_ALERT = "getalerts"
        const val VIDEO_URL = "videourl"
        const val REQUEST_GET_EXAMS = "getexams"
        const val REQUEST_GET_SCHEDULE = "getschedule"
        const val REUQEST_GET_SUBJECTS = "getsubjects"
        const val REQUEST_GET_DRIVE = "getdrive"
        const val REQUEST_VIEW_TYPE = "viewtype"
        const val REQUEST_SET_JOIN_LOG = "setjoinlog"
        const val REQUEST_SETFILE_VIEW_LOG = "setfileviewlog"
        const val REQUEST_SCHEDULE_ID = "scheduleid"
        const val KEY_ROOM_ID = "room_id"
        const val REQUEST_DEVICE = "Device"
        const val REQUEST_DEVICE_SMALL = "device"
        const val KEY_ANDROID = "A"
        const val REQUEST_HOMEAPI = "homeapi"
        const val REQUEST_SET_END_MEETING_LOG = "setendmeetinglog"
        const val REUQEST_SHARE_ID = "shareid"
        const val REQUEST_FILE_TITLE = "filetitle"
        const val REQUEST_FILE_DESCR = "filedescr"
        const val REQUEST_FILE_TYPE = "filetype"
        const val REQUEST_FILE_EXT = "fileext"
        const val REQUEST_FILE_SIZE = "filesize"
        const val REUQEST_UPLOAD_TYPE = "uploadtype"
        const val REQUEST_IMAGE = "Image "
        const val REQUEST_GETSUBJECTSBYSTANDARD = "getsubjectsbystandard"
        const val REQUEST_STANDARDID = "standardid"
        const val REQUEST_GETALLSTANDARDS = "getallstandards"
        const val REQUEST_DEVICE_DETAILS = "devicedetails"
        const val REQUEST_ADD_TO_DRIVE_WITH_LINK = "addtodrivewithlink"
        const val REQUEST_KW_TYPE = "kwtype"
        const val REQUEST_LINK_URL = "linkurl"
        const val REQUEST_OLD_PASSWORD = "oldpassword"
        const val REQUEST_NEW_PASSWORD = "newpassword"
        const val REQUEST_CHANGE_PASSWORD = "changepassword"
        const val REQUEST_UPDATE_USER_PROFILE = "updateuserprofile"
        const val REQUEST_LAST_NAME = "lastname"
        const val REQUEST_FIRST_NAME = "firstname"
        const val REQUEST_PHONE_1 = "phone1"
        const val REQUEST_EMAIL_ID = "emailid"
        const val REQUEST_GET_EXAM_QUESTION_BY_EXAM_ID = "getexamquestionbyexamid"
        const val REQUEST_UPDATE_EXAM_ANSWERS = "updateexamanswers"
        const val REQUEST_EXAM_ID = "examid"
        const val KEY_DURATION = "duration"
        const val KEY_MAKRS = "makrs"
        const val KEY_TIME = "time"
        const val REQUEST_SR_NO = "SrNo"
        const val REQUEST_OBJECTIVE_ANSWER = "objectiveanswer"
        const val REQUEST_SUBJECTIVE_ANSWER = "subjectiveanswer"
        const val KEY_FORMATED_TIME = "formatedtime"
        const val REQUEST_MODE_END_EXAM = "endexam"
        const val REQUEST_MODE_START_EXAM = "startexam"
        const val REQUEST_MODE_VIEW_RESULT = "viewexamresult"
        const val REQUEST_OPTION_A_VALUE = "optionAvalue"
        const val REQUEST_OPTION_B_VALUE = "optionBvalue"
        const val REQUEST_OPTION_C_VALUE = "optionCvalue"
        const val REQUEST_OPTION_D_VALUE = "optionDvalue"
        const val IMAGE_FULL_ZOOM_ANIM = "image_full_zoom_animation"
        const val REQUEST_QUESTION_ID = "questionid"
        const val KEY_OBTAIN_MARKS = "totalobtainedmarks"
        const val KEY_DRIVE_DATA = "key_drive_data"
        const val MODE_DELETE_DRIVE = "deletedrive"
        const val REQUEST_DRIVE_ID = "driveid"



    }
}